export const CHANNEL_LIST_REQUEST = 'CHANNEL_LIST_REQUEST'
export const CHANNEL_LIST_SUCCESS = 'CHANNEL_LIST_SUCCESS'
export const CHANNEL_LIST_FAIL = 'CHANNEL_LIST_FAIL'
export const CHANNEL_ACTIVE = 'CHANNEL_ACTIVE'
export const CHANNEL_SEARCH_LIST = 'CHANNEL_SEARCH_LIST'

export const CHANNEL_GET_SUCCESS = 'CHANNEL_GET_SUCCESS'
export const CHANNEL_CREATE_SUCCESS = 'CHANNEL_CREATE_SUCCESS'