export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST'
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS'

export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL'

export const MESSAGE_GET_SUCCESS = 'MESSAGE_GET_SUCCESS'

export const MESSAGE_CREATE_SUCCESS = 'MESSAGE_CREATE_SUCCESSS'

